-- Generated by nyrc 0.2.0 (NYR-Lang) from tools/nyr/standing_decay.nyr -- do not edit.
-- source sha256 587961caea76fa74752478a0ae550e89af4f7a6e5169cb9b46a9a94ecc7ab550
-- Lua 5.4.  M.evaluate(ctx) returns { spawns = {...}, signals = {...}, updates = {...} }: the actions
-- of every rule whose condition holds, in rule order.  ctx maps every name in M.INPUTS to a number
-- and every name in M.EXTERNAL_SETS to an array of numbers.  An update names an output and an op:
-- "set" replaces the value, "add" adds to it.

local M = {}

M.INPUTS = { "score", "rest", "now", "rate", "decayed_at", "period" }
M.EXTERNAL_SETS = {  }
M.OUTPUTS = { "decayed_at", "score" }
M.CONSTANTS = {}
M.SETS = {}

local function min2(a, b)
  if a < b then return a end
  return b
end

local function max2(a, b)
  if a > b then return a end
  return b
end

local function floor1(v)
  return v // 1.0
end

-- rule 0 (line 18): [score == rest]
local function rule_0(x)
  return x.score == x.rest
end

-- rule 1 (line 21): [score > rest] and [rate != 0] and [now - decayed_at >= period]
local function rule_1(x)
  return (x.score > x.rest) and (x.rate ~= 0.0) and (x.now - x.decayed_at >= x.period)
end

-- rule 2 (line 24): [score < rest] and [rate != 0] and [now - decayed_at >= period]
local function rule_2(x)
  return (x.score < x.rest) and (x.rate ~= 0.0) and (x.now - x.decayed_at >= x.period)
end

function M.evaluate(ctx)
  local missing = {}
  for _, name in ipairs(M.INPUTS) do
    if ctx[name] == nil then missing[#missing + 1] = name end
  end
  for _, name in ipairs(M.EXTERNAL_SETS) do
    if ctx[name] == nil then missing[#missing + 1] = name end
  end
  if #missing > 0 then error("missing inputs: " .. table.concat(missing, ", "), 2) end
  local x = {}
  for _, name in ipairs(M.INPUTS) do x[name] = ctx[name] * 1.0 end
  for _, name in ipairs(M.EXTERNAL_SETS) do x[name] = ctx[name] end
  local out = { spawns = {}, signals = {}, updates = {} }
  if rule_0(x) then  -- rule 0, line 18
    -- decayed_at <- now
    out.updates[#out.updates + 1] = { name = "decayed_at", op = "set", value = x.now }
  end
  if rule_1(x) then  -- rule 1, line 21
    -- decayed_at <- decayed_at + floor((now - decayed_at) / period) * period
    out.updates[#out.updates + 1] = { name = "decayed_at", op = "set", value = x.decayed_at + floor1((x.now - x.decayed_at) / x.period) * x.period }
    -- score <- max(rest, score - floor((now - decayed_at) / period) * rate)
    out.updates[#out.updates + 1] = { name = "score", op = "set", value = max2(x.rest, x.score - floor1((x.now - x.decayed_at) / x.period) * x.rate) }
  end
  if rule_2(x) then  -- rule 2, line 24
    -- decayed_at <- decayed_at + floor((now - decayed_at) / period) * period
    out.updates[#out.updates + 1] = { name = "decayed_at", op = "set", value = x.decayed_at + floor1((x.now - x.decayed_at) / x.period) * x.period }
    -- score <- min(rest, score + floor((now - decayed_at) / period) * rate)
    out.updates[#out.updates + 1] = { name = "score", op = "set", value = min2(x.rest, x.score + floor1((x.now - x.decayed_at) / x.period) * x.rate) }
  end
  return out
end

return M
