return {
    { name = "timeout callback resurrects cancelled work", file = "adapter/readiness.lua",
      old = 'if self.generation ~= generation then pcall(request.fail, outcome("world_changed"))',
      new = 'if false then pcall(request.fail, outcome("world_changed"))', spec = "spec/readiness_spec.lua" },
    { name = "native failure strands spawn readiness lease", file = "adapter/spawn.lua",
      old = 'if NyrWorldRelease then pcall(NyrWorldRelease, lease) end',
      new = 'if false then pcall(NyrWorldRelease, lease) end', spec = "spec/spawn_spec.lua" },
    { name = "signed timer rollover retains a pending response", file = "adapter/client_state.lua",
      old = 'if elapsed < 0 or elapsed >= self._timeout then',
      new = 'if elapsed >= self._timeout then', spec = "spec/readiness_spec.lua" },
    { name = "world request ignores collision", file = "adapter/readiness.lua",
      old = "and facts.network == true and facts.ped == true and facts.collision == true",
      new = "and facts.network == true and facts.ped == true", spec = "spec/readiness_spec.lua" },
    { name = "old server epoch dispatches", file = "adapter/bridge.lua",
      old = "if epoch and asked_epoch ~= epoch then", new = "if false then", spec = "spec/bridge_spec.lua" },
    { name = "drain overlaps the old database write", file = "adapter/drain.lua",
      old = 'self.status == "WAITING" and not self.opts.busy()', new = 'self.status == "WAITING"',
      spec = "spec/drain_spec.lua" },
    { name = "drain accepts a late completion", file = "adapter/drain.lua",
      old = 'if self:expired() then\n                self.status = "UNKNOWN"', new = 'if false then\n                self.status = "UNKNOWN"',
      spec = "spec/drain_spec.lua" },
    { name = "storage guard follows the new resource path", file = "adapter/storage_guard.lua",
      old = "if not current then self.blocked = true",
      new = "if current then current.path = self.first.path end\n    if not current then self.blocked = true", spec = "spec/storage_guard_spec.lua" },
    { name = "late reply reaches a stale callback", file = "adapter/client_state.lua",
      old = "self._pending = {}\n    for _, waiting in pairs(pending)", new = "self._pending = pending\n    for _, waiting in pairs(pending)",
      spec = "spec/readiness_spec.lua" },
}
